# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "attachments", :force => true do |t|
    t.integer  "comment_id"
    t.string   "filename"
    t.string   "content_type"
    t.integer  "size"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "changes", :force => true do |t|
    t.integer  "changeset_id"
    t.string   "path"
    t.string   "status"
    t.string   "from_path"
    t.integer  "from_revision"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "changesets", :force => true do |t|
    t.integer  "repository_id"
    t.integer  "revision"
    t.string   "author"
    t.text     "log"
    t.datetime "revised_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "milestones", :force => true do |t|
    t.integer  "project_id"
    t.string   "name"
    t.text     "info"
    t.datetime "completed_at"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "permissions", :force => true do |t|
    t.integer  "user_id"
    t.integer  "project_id"
    t.boolean  "view_changesets"
    t.boolean  "add_changesets"
    t.boolean  "view_repository"
    t.boolean  "view_milestones"
    t.boolean  "add_milestones"
    t.boolean  "update_milestones"
    t.boolean  "remove_milestones"
    t.boolean  "view_tickets"
    t.boolean  "add_tickets"
    t.boolean  "update_tickets"
    t.boolean  "remove_tickets"
    t.boolean  "alter_tickets"
    t.boolean  "add_projects"
    t.boolean  "edit_projects"
    t.boolean  "remove_projects"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "project_ticket_attributes", :force => true do |t|
    t.integer  "project_id"
    t.integer  "ticket_attribute_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "projects", :force => true do |t|
    t.integer  "repository_id"
    t.string   "name"
    t.text     "info"
    t.boolean  "closed",        :default => false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "repositories", :force => true do |t|
    t.string   "name"
    t.string   "path"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "ticket_attributes", :force => true do |t|
    t.string   "type"
    t.string   "name"
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "resolved"
  end

  create_table "ticket_changes", :force => true do |t|
    t.integer  "comment_id"
    t.string   "attribute_name"
    t.string   "old_value"
    t.string   "new_value"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "ticket_comments", :force => true do |t|
    t.integer  "author_id"
    t.integer  "ticket_id"
    t.text     "content"
    t.string   "public_author_text"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tickets", :force => true do |t|
    t.integer  "milestone_id"
    t.integer  "component_id"
    t.integer  "priority_id"
    t.integer  "release_id"
    t.integer  "status_id"
    t.integer  "user_id"
    t.integer  "project_id"
    t.integer  "assigned_user_id"
    t.string   "public_author_text"
    t.text     "summary"
    t.text     "content"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", :force => true do |t|
    t.string   "login"
    t.string   "email"
    t.string   "crypted_password",          :limit => 40
    t.string   "salt",                      :limit => 40
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "remember_token"
    t.datetime "remember_token_expires_at"
    t.string   "activation_code",           :limit => 40
    t.datetime "activated_at"
  end

end
